version: '3'

services:
  remote_player:
    image: ghcr.io/moimart/assistant_client:latest
    restart: always
    network_mode: "host"
    environment:
      - PYTHONUNBUFFERED=1
      - AUDIO_DEVICE_INDEX=${AUDIO_DEVICE_INDEX}
      - WAKE_WORD_MODEL=${WAKE_WORD_MODEL}
      - ASSISTANT_HOST=${ASSISTANT_HOST}
    volumes:
      - ./cache:/app/cache
    devices:
      - /dev/snd:/dev/snd
    group_add:
      - audio

