version: '3'

services:
  remote_player:
    image: ghcr.io/moimart/assistant_server:latest
    network_mode: "host"
    restart: always
    environment:
      - PYTHONUNBUFFERED=1
      - HOST_IP=${HOST_IP}
      - HASS_TOKEN=${HASS_TOKEN}
      - HASS_HOST=${HASS_HOST}
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - USER_NAME=${USER_NAME}
      - BROADCASTER_IP=${BROADCASTER_IP}
      - BROADCASTER_PORT=${BROADCASTER_PORT}

