version: '3'

services:
  remote_player:
    image: ghcr.io/moimart/remote_broadcaster:latest
    network_mode: "host"
    restart: always
    environment:
      - PYTHONUNBUFFERED=1
      - HOST_IP=${HOST_IP}
      - BROADCASTER_TOKEN=${BROADCASTER_TOKEN}
      - ALLOWED_NETWORK=${ALLOWED_NETWORK}

